### ISSUE TITLE
Does conda work?

### ISSUE THREAD

**Issue by claytharrison** [wyuenho/emacs-pet#32]
Feels like a bit of a stupid question, but while conda/mamba/micromamba aren't listed in the README as supported, I can see that there's code handling them in pet.el. I tried getting pet-mode working with my micromamba setup and haven't had any luck, just wanted to know if I should keep trying at this or if conda support just isn't fully working yet.

**Comment by wyuenho** [comment]
What's failing? Have you tried [debug](https://github.com/wyuenho/emacs-pet/blob/main/pet.el#L56) mode and see what error pops up?

**Comment by wyuenho** [comment]
conda and mamba should have worked, but micromamba probably didn't as the command line interface have drifted between them. I've just pushed a fix (87807febc13c5964ca74ba789854b7212a605b2a) and it should work now.

**Comment by claytharrison** [comment]
I've gotten back around to trying this again, first I had to install `dasel`, which is something I missed first go-around. So nothing to do with conda/micromamba specifically. Unfortunately it's still failing to detect my micromamba envs, prompting me to create them from the `.yml` file when they already exist. I've figured out the problem there too but I'll make a separate issue for it.

**Comment by wyuenho** [comment]
I look forward to it. It's be nice to see an example of your environment.yml file, your project structure and your environment variables etc as well.
